baseURL = "https://www.duncanmcconstruction.com"
languageCode = "en-us"
title = "DUNCAN MC CONSTRUCTION, LLC"

contentDir = "content"

languageLang = "en"
copyright = "Copyright &copy; {year} Duncan Mc Construction, LLC, all rights reserved"
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Services"
weight = 1
identifier = "Services"
url = "services"

[[menu.main]]
name = "About"
weight = 2
identifier = "About"
url = "about"

# [[menu.main]]
# name = "Contact us"
# weight = 3
# identifier = "Contact Us"
# url = "contact-us"