baseURL = "https://www.duncanmcconstruction.com"
languageCode = "en-us"
title = "DUNCAN MC CONSTRUCTION, LLC"

contentDir = "content"

languageLang = "en"
copyright = "Copyright &copy; {year} Duncan Mc Construction, LLC, all rights reserved"
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params.logo]
mobile = "images/dmc-logo.png"
mobile_height = "106"
mobile_width = "250"
alt = "Duncan MC Construction, LLC"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Flooring"
weight = 1
identifier = "Flooring"
url = "/flooring-installation/"

[[menu.main]]
name = "Hardwood Flooring"
weight = 2
identifier = "Hardwood Flooring"
url = "/hardwood-flooring/"
parent = "Flooring"

[[menu.main]]
name = "Laminate Flooring"
weight = 3
identifier = "Laminate Flooring"
url = "/laminate-flooring/"
parent = "Flooring"

[[menu.main]]
name = "Vinyl Flooring"
weight = 4
identifier = "Vinyl Flooring"
url = "/vinyl-flooring/"
parent = "Flooring"

[[menu.main]]	
name = "Home Remodels"
weight = 5
identifier = "Home Remodels"
url = "/bathroom-and-kitchen-remodels/"

[[menu.main]]
name = "Home Repairs"
weight = 6
identifier = "Home Repairs"
url = "/residential-home-repairs/"

[[menu.main]]
name = "Contact Us"
weight = 7
identifier = "Contact Us"
url = "/contact/"
