baseURL = "http://duncanmcconstruction.com/"
languageCode = "en-us"
title = "DUNCAN MC CONSTRUCTION, LLC"

contentDir = "content"

languageLang = "en"
copyright = "Copyright &copy; {year} Duncan Mc Construction, LLC, all rights reserved."
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[[menu.main]]
name = "Home"
weight = 1
identifier = "Home"
url = "/"

[[menu.main]]
name = "Services"
weight = 2
identifier = "Services"
url = "#"

[[menu.main]]
name = "Contact us"
weight = 5
identifier = "Contact Us"
url = "contact-us"
